services:
  - type: web
    name: mycv-app
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_PSW
        sync: false
      - key: SECRET
        sync: false